name: Android E2E

on:
  pull_request:

jobs:
  android-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    env:
      CI: true
      EXPO_NO_TELEMETRY: 1
      APP_ID: com.yourcompany.yourapp # set your real applicationId if you use it in flows

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Hardware accel for faster emulator boot (recommended on ubuntu runners)
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Gradle config & dependency caching (recommended by emulator-runner docs)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Install root dependencies
        run: npm ci

      - name: Install example dependencies
        working-directory: example
        run: npm ci

      # Install Maestro CLI (no action needed)
      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      # Optional: cache AVD to speed up subsequent boots
      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/
