name: Android E2E

on:
  pull_request:

jobs:
  android-build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    env:
      CI: true
      EXPO_NO_TELEMETRY: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install root dependencies
        run: npm ci

      - name: Install example dependencies
        working-directory: example
        run: npm ci

      - name: Expo Prebuild Android project
        working-directory: example
        run: npx expo prebuild --platform android --no-install

      - name: Assemble Debug APK
        working-directory: example/android
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: example/android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error

  android-e2e:
    runs-on: ubuntu-latest
    needs: android-build
    timeout-minutes: 40
    env:
      CI: true
      EXPO_NO_TELEMETRY: 1
      APP_ID: com.yourcompany.yourapp # update if referenced in flows

    steps:
      - name: Checkout (for Maestro flows, etc.)
        uses: actions/checkout@v4

      # Hardware acceleration for the emulator
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-debug-apk
          path: ./apk

      - name: Run Android E2E tests (Expo + Maestro)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          arch: x86_64
          profile: pixel
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            adb wait-for-device
            adb install -r ./apk/app-debug.apk
            maestro --version
            maestro test --format junit --output ./maestro-report.xml maestro/smoke.yaml

      - name: Upload Maestro report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maestro-results
          path: maestro-report.xml
